# docker-compose up --build --force-recreate
# docker-compose up --detach --build --force-recreate
# docker-compose logs --follow --tail=100

version: "3.7"

volumes:
  maildev-development-data:
    name: maildev-development-data

networks:
  maildev-development-network:
    name: maildev-development-network
    driver: bridge

x-common: &common
  restart: unless-stopped
  networks:
    - maildev-development-network

services:

  maildev-development:
    <<: *common
    build:
      context: .
      dockerfile: ./docker/Dockerfile-development
    image: maildev-development-local:default
    container_name: maildev-development-local
    volumes:
      - type: volume
        source: maildev-development-data
        target: /var/maildev/data
      - type: bind
        source: .
        target: /wd/maildev
        volume:
          nocopy: true
    ports:
      - 127.0.0.1:9025:1025 # smtp
      - 127.0.0.1:9080:1080 # ui
