FROM node:10-alpine
USER root
ENV NODE_ENV development
#WORKDIR /
#COPY ./docker/entrypoint-development.sh /
#RUN chmod 755 /entrypoint-development.sh
WORKDIR /maildev
ENTRYPOINT /bin/sh /maildev/docker/entrypoint-development.sh